apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: doctor-app
type: Opaque
data:
  uri: bW9uZ29kYjovL2xvY2FsaG9zdCoyNzAxNy9hcHBvaW50bWVudA==  # mongodb://localhost:27017/appointment (base64 encoded)
