apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
  namespace: doctor-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: doctor-app
